#!/usr/bin/env python
"""ai-collab CLI — setup wizard and management for multi-AI collaboration.

Usage:
    ai-collab init              Interactive first-time setup wizard
    ai-collab seed              Seed database with default agent/workflow/tool data
    ai-collab agents            List configured agents and their status
    ai-collab tui "question"    Launch real-time TUI with streaming agent panels

Options:
    --non-interactive           Skip prompts, use all detected agents with defaults
"""

import argparse
import json
import os
import platform
import re
import shutil
import sys
from pathlib import Path

_VALID_AGENT_NAME = re.compile(r"^[a-z][a-z0-9_-]*$")

# ---------------------------------------------------------------------------
# TOML support: use tomllib (3.11+) for reading, hand-write for generating
# (no external dependency needed — we only *write* TOML in this CLI)
# ---------------------------------------------------------------------------

_PROJECT_DIR = Path(__file__).resolve().parent
_CONFIG_FILE = _PROJECT_DIR / "ai-collab.toml"
_DB_PATH = _PROJECT_DIR / ".data" / "brainstorm.db"

# ---------------------------------------------------------------------------
# Known agent definitions (CLI detection + config defaults)
# ---------------------------------------------------------------------------

KNOWN_AGENTS = {
    "copilot": {
        "command": "copilot",
        "args": ["-p", "{prompt}", "--allow-all"],
        "display_name": "GitHub Copilot",
        "description": "Code analysis, shell commands, git operations, GitHub CLI",
    },
    "gemini": {
        "command": "gemini",
        "args": ["-p", "{prompt}", "--yolo"],
        "display_name": "Google Gemini",
        "description": "Architecture analysis, research, alternative approaches, documentation",
    },
    "codex": {
        "command": "codex",
        "args": ["-p", "{prompt}", "--full-auto"],
        "display_name": "OpenAI Codex",
        "description": "Code generation and autonomous execution",
    },
    "aider": {
        "command": "aider",
        "args": ["--message", "{prompt}"],
        "display_name": "Aider",
        "description": "AI pair programming with git integration",
    },
}

# Claude is always listed but noted as the orchestrator, not a delegate agent.
ORCHESTRATOR = {
    "name": "claude",
    "command": "claude",
    "display_name": "Claude Code",
    "note": "orchestrator — not dispatched as a delegate agent",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _find_cli(name: str) -> str | None:
    """Find a CLI executable on PATH. On Windows, also check .cmd variants."""
    if sys.platform == "win32":
        found = shutil.which(f"{name}.cmd") or shutil.which(name)
    else:
        found = shutil.which(name)
    return found


def _detect_agents() -> dict[str, str | None]:
    """Scan PATH for all known agent CLIs plus the orchestrator.

    Returns a dict mapping agent key -> resolved path (or None if not found).
    """
    detected: dict[str, str | None] = {}
    for key in KNOWN_AGENTS:
        detected[key] = _find_cli(KNOWN_AGENTS[key]["command"])
    detected["claude"] = _find_cli(ORCHESTRATOR["command"])
    return detected


def _prompt_yes_no(question: str, default: bool = True) -> bool:
    suffix = " [Y/n] " if default else " [y/N] "
    while True:
        answer = input(question + suffix).strip().lower()
        if answer == "":
            return default
        if answer in ("y", "yes"):
            return True
        if answer in ("n", "no"):
            return False
        print("  Please answer y or n.")


def _prompt_choice(prompt_text: str, options: list[str], default: str | None = None) -> str:
    print(prompt_text)
    for i, opt in enumerate(options, 1):
        marker = " (default)" if opt == default else ""
        print(f"  {i}. {opt}{marker}")
    while True:
        raw = input("Choice: ").strip()
        if raw == "" and default is not None:
            return default
        try:
            idx = int(raw)
            if 1 <= idx <= len(options):
                return options[idx - 1]
        except ValueError:
            if raw in options:
                return raw
        print(f"  Enter a number 1-{len(options)} or one of: {', '.join(options)}")


def _write_toml(agents: list[dict], path: Path) -> None:
    """Write ai-collab.toml with [agents.NAME] table format.

    We hand-write TOML to avoid depending on any external library for writing.
    Uses [agents.NAME] table format (not [[agents]] array of tables) to match
    what config.py expects.
    """
    lines = [
        "# ai-collab configuration",
        "# Generated by: ai-collab init",
        f"# Platform: {platform.system()} {platform.release()}",
        "",
        "[settings]",
        'db_path = ".data/brainstorm.db"',
        "default_timeout = 900",
        "",
    ]

    for agent in agents:
        name = agent["name"]
        if not _VALID_AGENT_NAME.match(name):
            raise ValueError(f"Invalid agent name '{name}': must match [a-z][a-z0-9_-]*")
        lines.append(f"[agents.{name}]")
        lines.append(f'enabled = {str(agent["enabled"]).lower()}')
        lines.append(f'command = "{agent["command"]}"')

        # args as a TOML array
        args_str = ", ".join(f'"{a}"' for a in agent["args"])
        lines.append(f"args = [{args_str}]")

        lines.append(f'display_name = "{agent["display_name"]}"')

        # Escape any double quotes in description
        desc = agent["description"].replace('"', '\\"')
        lines.append(f'description = "{desc}"')

        if agent.get("model"):
            lines.append(f'model = "{agent["model"]}"')
        if agent.get("timeout"):
            lines.append(f"timeout = {agent['timeout']}")

        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def _read_toml(path: Path) -> dict | None:
    """Read a TOML file. Returns parsed dict or None on failure."""
    if not path.exists():
        return None
    try:
        # Python 3.11+
        import tomllib
        with open(path, "rb") as f:
            return tomllib.load(f)
    except ImportError:
        pass
    # Fallback: try tomli (pip install tomli)
    try:
        import tomli  # type: ignore[import-untyped]
        with open(path, "rb") as f:
            return tomli.load(f)
    except ImportError:
        pass
    # Last resort: basic manual parse for our simple format
    return None


# ---------------------------------------------------------------------------
# Seed command
# ---------------------------------------------------------------------------

def _run_seed() -> dict:
    """Seed the brainstorm DB with default agent definitions, workflow templates,
    and tool guides. Returns counts of seeded records.
    """
    from brainstorm_db import BrainstormDB
    from brainstorm_seeds import AGENT_DEFINITIONS, TOOL_GUIDES, WORKFLOW_TEMPLATES

    db = BrainstormDB(_DB_PATH)
    counts = {"agents": 0, "workflows": 0, "tools": 0}
    try:
        for defn in AGENT_DEFINITIONS:
            db.upsert_agent_definition(**defn)
            counts["agents"] += 1
        for wf in WORKFLOW_TEMPLATES:
            phases_json = json.dumps(wf["phases"])
            db.upsert_workflow_template(
                name=wf["name"],
                overview=wf["overview"],
                phases_json=phases_json,
                convergence_rules=wf["convergence_rules"],
                response_format=wf["response_format"],
            )
            counts["workflows"] += 1
        for guide in TOOL_GUIDES:
            db.upsert_tool_guide(**guide)
            counts["tools"] += 1
    finally:
        db.close()
    return counts


# ---------------------------------------------------------------------------
# MCP config snippet generation
# ---------------------------------------------------------------------------

def _mcp_snippet_claude() -> dict:
    """JSON snippet for Claude Code's MCP settings (mcp_server.py)."""
    server_path = str(_PROJECT_DIR / "mcp_server.py")
    return {
        "ai-collab": {
            "type": "stdio",
            "command": "python",
            "args": [server_path],
        }
    }


def _mcp_snippet_agent(agent_name: str) -> dict:
    """JSON snippet for an agent's MCP config (brainstorm_server.py)."""
    server_path = str(_PROJECT_DIR / "brainstorm_server.py")
    return {
        "brainstorm": {
            "type": "stdio",
            "command": "python",
            "args": [server_path],
        }
    }


def _print_mcp_config(enabled_agents: list[str]) -> None:
    """Print MCP configuration snippets to stdout."""
    print()
    print("=" * 64)
    print("MCP Configuration Snippets")
    print("=" * 64)

    # Claude Code config
    print()
    print("1) Claude Code  (add to your MCP settings)")
    print("   Location: ~/.claude.json  or  project .mcp.json")
    print()
    snippet = _mcp_snippet_claude()
    print(json.dumps(snippet, indent=2))

    # Agent configs
    config_locations = {
        "copilot": "~/.copilot/mcp-config.json",
        "gemini": ".gemini/settings.json (project-level)",
        "codex": "codex MCP config (see codex docs)",
        "aider": "aider MCP config (see aider docs)",
    }

    for agent in enabled_agents:
        if agent == "claude":
            continue
        loc = config_locations.get(agent, f"{agent} MCP config")
        print()
        print(f"2) {KNOWN_AGENTS.get(agent, {}).get('display_name', agent)}  (add brainstorm server)")
        print(f"   Location: {loc}")
        print()
        snippet = _mcp_snippet_agent(agent)
        print(json.dumps(snippet, indent=2))

    print()
    print("-" * 64)
    print("Copy the JSON above into the appropriate config files.")
    print("All agents share the same brainstorm.db via brainstorm_server.py.")
    print("-" * 64)


# ---------------------------------------------------------------------------
# init command — interactive setup wizard
# ---------------------------------------------------------------------------

def _cmd_init(args: argparse.Namespace) -> None:
    non_interactive = args.non_interactive

    # ── Step 1: Welcome ──────────────────────────────────────────────
    print()
    print("=" * 64)
    print("  ai-collab Setup Wizard")
    print("=" * 64)
    print()
    print("ai-collab orchestrates multi-AI brainstorming sessions.")
    print("Multiple AI agents (Copilot, Gemini, Codex, Aider, etc.)")
    print("collaborate through a shared SQLite database, with Claude")
    print("Code acting as the orchestrator.")
    print()
    print("This wizard will:")
    print("  1. Detect installed AI CLI tools")
    print("  2. Let you choose which agents to enable")
    print("  3. Generate ai-collab.toml configuration")
    print("  4. Show MCP config snippets for each tool")
    print("  5. Seed the database with defaults")
    print()

    if not non_interactive:
        if not _prompt_yes_no("Continue?"):
            print("Aborted.")
            return

    # ── Step 2: Detect CLIs ──────────────────────────────────────────
    print()
    print("Scanning PATH for AI CLI tools...")
    print()

    detected = _detect_agents()

    # Display results
    found_any = False
    for key, path in detected.items():
        if key == "claude":
            label = f"{ORCHESTRATOR['display_name']} ({ORCHESTRATOR['note']})"
        else:
            label = KNOWN_AGENTS[key]["display_name"]

        if path:
            found_any = True
            print(f"  [x] {label}")
            print(f"      {path}")
        else:
            print(f"  [ ] {label}  (not found)")

    print()

    if not found_any:
        print("No AI CLI tools were detected on PATH.")
        print("You can still configure agents manually.")
        print()

    # ── Step 3: Agent selection ──────────────────────────────────────
    # Build list of agents to enable
    enabled_agents: list[dict] = []
    detected_keys = [k for k in KNOWN_AGENTS if detected.get(k)]

    if non_interactive:
        # Non-interactive: enable all detected agents with defaults
        for key in detected_keys:
            info = KNOWN_AGENTS[key]
            enabled_agents.append({
                "name": key,
                "command": info["command"],
                "args": list(info["args"]),
                "display_name": info["display_name"],
                "description": info["description"],
                "enabled": True,
                "model": None,
                "timeout": None,
            })
        print(f"Non-interactive mode: enabling {len(enabled_agents)} detected agent(s).")
    else:
        # Interactive: let user pick from detected agents
        if detected_keys:
            print("Select which detected agents to enable:")
            print()
            for key in detected_keys:
                info = KNOWN_AGENTS[key]
                enable = _prompt_yes_no(f"  Enable {info['display_name']}?")
                if enable:
                    enabled_agents.append({
                        "name": key,
                        "command": info["command"],
                        "args": list(info["args"]),
                        "display_name": info["display_name"],
                        "description": info["description"],
                        "enabled": True,
                        "model": None,
                        "timeout": None,
                    })
            print()

        # Offer to add undetected known agents
        undetected_keys = [k for k in KNOWN_AGENTS if not detected.get(k)]
        if undetected_keys:
            if _prompt_yes_no("Add any agents that were not detected on PATH?", default=False):
                for key in undetected_keys:
                    info = KNOWN_AGENTS[key]
                    if _prompt_yes_no(f"  Add {info['display_name']} (not detected)?", default=False):
                        cmd = input(f"    Command [{info['command']}]: ").strip() or info["command"]
                        enabled_agents.append({
                            "name": key,
                            "command": cmd,
                            "args": list(info["args"]),
                            "display_name": info["display_name"],
                            "description": info["description"],
                            "enabled": True,
                            "model": None,
                            "timeout": None,
                        })
                print()

        # Offer to add fully custom agents
        while True:
            if not _prompt_yes_no("Add a custom agent definition?", default=False):
                break
            name = input("  Agent name (short identifier, lowercase letters/numbers/-/_): ").strip()
            if not name:
                print("  Skipped (no name given).")
                continue
            if not _VALID_AGENT_NAME.match(name):
                print(f"  Invalid name '{name}': must match [a-z][a-z0-9_-]* (e.g. 'my-agent')")
                continue
            command = input("  Command to run: ").strip()
            if not command:
                print("  Skipped (no command given).")
                continue
            args_raw = input('  Args pattern (comma-separated, use {prompt} placeholder) ["-p","{prompt}"]: ').strip()
            if args_raw:
                agent_args = [a.strip().strip('"').strip("'") for a in args_raw.split(",")]
            else:
                agent_args = ["-p", "{prompt}"]
            display = input(f"  Display name [{name.title()}]: ").strip() or name.title()
            desc = input("  Description: ").strip() or f"Custom agent: {name}"
            enabled_agents.append({
                "name": name,
                "command": command,
                "args": agent_args,
                "display_name": display,
                "description": desc,
                "enabled": True,
                "model": None,
                "timeout": None,
            })
            print(f"  Added {display}.")
            print()

    if not enabled_agents:
        print("No agents enabled. You can re-run 'ai-collab init' later.")
        print()

    # ── Step 4: Generate ai-collab.toml ──────────────────────────────
    if enabled_agents:
        if _CONFIG_FILE.exists() and not non_interactive:
            if not _prompt_yes_no(f"Overwrite existing {_CONFIG_FILE.name}?"):
                print("  Keeping existing config.")
            else:
                _write_toml(enabled_agents, _CONFIG_FILE)
                print(f"  Wrote {_CONFIG_FILE}")
        else:
            _write_toml(enabled_agents, _CONFIG_FILE)
            print(f"  Wrote {_CONFIG_FILE}")
        print()

    # ── Step 5: MCP config snippets ──────────────────────────────────
    agent_names = [a["name"] for a in enabled_agents]
    _print_mcp_config(agent_names)

    # ── Step 6: Seed database ────────────────────────────────────────
    print()
    do_seed = non_interactive or _prompt_yes_no("Seed database with default agent definitions, workflows, and tool guides?")
    if do_seed:
        print("Seeding database...")
        counts = _run_seed()
        print(f"  Seeded: {counts['agents']} agent definitions, "
              f"{counts['workflows']} workflow templates, "
              f"{counts['tools']} tool guides")
        print(f"  Database: {_DB_PATH}")
    print()

    # ── Step 7: Summary ──────────────────────────────────────────────
    print("=" * 64)
    print("  Setup Complete")
    print("=" * 64)
    print()
    if enabled_agents:
        print(f"Enabled agents ({len(enabled_agents)}):")
        for a in enabled_agents:
            status = "enabled" if a["enabled"] else "disabled"
            print(f"  - {a['display_name']} ({a['name']}) [{status}]")
    else:
        print("No agents configured.")
    print()
    print("Next steps:")
    print("  1. Copy the MCP config snippets above into the appropriate files")
    print("  2. Restart Claude Code (and other agents) to pick up the new config")
    print("  3. Run a brainstorm: use /multi-ai-brainstorm or the bs_* MCP tools")
    print()
    if not do_seed:
        print("  Tip: Run 'ai-collab seed' to populate the database with defaults.")
        print()


# ---------------------------------------------------------------------------
# seed command
# ---------------------------------------------------------------------------

def _cmd_seed(args: argparse.Namespace) -> None:
    print("Seeding database with defaults...")
    counts = _run_seed()
    print(f"  Seeded: {counts['agents']} agent definitions, "
          f"{counts['workflows']} workflow templates, "
          f"{counts['tools']} tool guides")
    print(f"  Database: {_DB_PATH}")


# ---------------------------------------------------------------------------
# agents command
# ---------------------------------------------------------------------------

def _cmd_agents(args: argparse.Namespace) -> None:
    # 1. Show agents from config file (if exists)
    config = _read_toml(_CONFIG_FILE)
    config_agents: list[dict] = []
    if config and "agents" in config:
        agents_data = config["agents"]
        if isinstance(agents_data, dict):
            # [agents.NAME] format → dict of dicts
            for name, data in agents_data.items():
                if isinstance(data, dict):
                    data["name"] = name
                    config_agents.append(data)
        elif isinstance(agents_data, list):
            # [[agents]] format → list of dicts (legacy)
            config_agents = agents_data

    # 2. Show agents from DB (if seeded)
    db_agents: list[dict] = []
    if _DB_PATH.exists():
        try:
            from brainstorm_db import BrainstormDB
            db = BrainstormDB(_DB_PATH)
            db_agents = db.list_agent_definitions()
            db.close()
        except Exception:
            pass

    # 3. Detect on PATH
    detected = _detect_agents()

    print()
    print("=" * 64)
    print("  ai-collab Agents")
    print("=" * 64)
    print()

    # Config file agents
    if config_agents:
        print(f"From ai-collab.toml ({len(config_agents)} configured):")
        for a in config_agents:
            name = a.get("name", "?")
            display = a.get("display_name", name)
            enabled = a.get("enabled", True)
            cmd = a.get("command", "?")
            on_path = _find_cli(cmd) is not None
            status_parts = []
            if enabled:
                status_parts.append("enabled")
            else:
                status_parts.append("disabled")
            if on_path:
                status_parts.append("on PATH")
            else:
                status_parts.append("NOT on PATH")
            print(f"  {display} ({name}): {', '.join(status_parts)}")
            print(f"    command: {cmd}")
            desc = a.get("description", "")
            if desc:
                print(f"    description: {desc}")
        print()
    else:
        print("No agents configured in ai-collab.toml.")
        if not _CONFIG_FILE.exists():
            print("  Run 'ai-collab init' to set up.")
        print()

    # DB agents
    if db_agents:
        print(f"From database ({len(db_agents)} agent definitions):")
        for a in db_agents:
            print(f"  {a['display_name']} ({a['agent_name']})")
            cap = a.get("capabilities", "")
            if cap:
                # Truncate long capabilities
                if len(cap) > 100:
                    cap = cap[:97] + "..."
                print(f"    capabilities: {cap}")
        print()
    else:
        if _DB_PATH.exists():
            print("No agent definitions in database. Run 'ai-collab seed'.")
        else:
            print("Database not initialized. Run 'ai-collab init' or 'ai-collab seed'.")
        print()

    # PATH detection
    print("CLI detection (current PATH):")
    for key, path in detected.items():
        if key == "claude":
            label = ORCHESTRATOR["display_name"]
        else:
            label = KNOWN_AGENTS[key]["display_name"]
        if path:
            print(f"  [x] {label}: {path}")
        else:
            print(f"  [ ] {label}: not found")
    print()


# ---------------------------------------------------------------------------
# tui command
# ---------------------------------------------------------------------------

def _cmd_tui(args: argparse.Namespace) -> None:
    try:
        from ai_collab_tui import run_tui
    except ImportError:
        print("Error: TUI requires the 'textual' package.")
        print("Install it with: pip install ai-collab[tui]")
        sys.exit(1)

    run_tui(hours=getattr(args, "hours", 24), limit=getattr(args, "limit", 6))


def _cmd_dispatch(args: argparse.Namespace) -> None:
    """Send a question to the TUI queue (for testing or scripting)."""
    from ai_collab_tui import dispatch_to_tui
    req_id = dispatch_to_tui(args.question, cwd=args.cwd)
    print(f"Dispatched to TUI: {req_id}")
    print(f"  Question: {args.question[:80]}")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="ai-collab",
        description="Multi-AI collaboration setup and management CLI",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  ai-collab init                  Interactive setup wizard\n"
            "  ai-collab init --non-interactive Auto-configure with defaults\n"
            "  ai-collab seed                  Seed database with defaults\n"
            "  ai-collab agents                List configured agents\n"
        ),
    )

    sub = parser.add_subparsers(dest="command")

    # init
    p_init = sub.add_parser(
        "init",
        help="Interactive setup wizard for first-time configuration",
    )
    p_init.add_argument(
        "--non-interactive",
        action="store_true",
        default=False,
        help="Skip prompts; use all detected agents with defaults (for CI)",
    )

    # seed
    sub.add_parser(
        "seed",
        help="Seed database with default agent definitions, workflows, and tool guides",
    )

    # agents
    sub.add_parser(
        "agents",
        help="List configured agents and their status",
    )

    # tui
    p_tui = sub.add_parser(
        "tui",
        help="Launch live feed monitor (stays open, watches for brainstorm rounds)",
    )
    p_tui.add_argument(
        "question",
        nargs="?",
        default=None,
        help="Optional: run this question immediately on start",
    )
    p_tui.add_argument(
        "--agents", "-a",
        help="Comma-separated list of agent names (default: all enabled)",
    )
    p_tui.add_argument(
        "--cwd", "-d",
        help="Ignored — kept for backward compatibility",
    )
    p_tui.add_argument(
        "--hours",
        type=int,
        default=24,
        help="Hours of history to show (default: 24)",
    )
    p_tui.add_argument(
        "--limit",
        type=int,
        default=6,
        help="Max sessions to display (default: 6)",
    )

    # dispatch (send a question to the running TUI)
    p_dispatch = sub.add_parser(
        "dispatch",
        help="Send a question to the running TUI from another terminal",
    )
    p_dispatch.add_argument("question", help="The question to dispatch")
    p_dispatch.add_argument(
        "--cwd", "-d",
        help="Working directory for agent subprocesses",
    )

    args = parser.parse_args()

    if args.command is None:
        parser.print_help()
        sys.exit(0)

    if args.command == "init":
        _cmd_init(args)
    elif args.command == "seed":
        _cmd_seed(args)
    elif args.command == "agents":
        _cmd_agents(args)
    elif args.command == "tui":
        _cmd_tui(args)
    elif args.command == "dispatch":
        _cmd_dispatch(args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
